name: masmorra_ascii
version: 0.37.0
description: Masmorra ASCII - Step 37 - Encerramento (solução final em masmorra_ascii)
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
