name: masmorra_ascii
description: Capítulo 22 - Economia, drops, preços e balanceamento
version: 0.22.0

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
