name: masmorra_ascii
description: Capítulo 28 - Refatoração com código organizado em pastas
version: 0.28.0

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
