name: masmorra_ascii
version: 0.32.0
description: Masmorra ASCII - Step 32 - Golden Tests e HUD Polido
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
