name: masmorra_ascii
version: 0.31.0
description: Masmorra ASCII - Step 31 - Persistência em JSON
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
