flowchart TB
  LJ[LoopJogo — Controller]
  LJ --> EJ[EstadoJogo]
  LJ --> MM[MapaMasmorra]
  MM --> GM[GeradorMasmorra]
  MM --> CV[CampoVisao]
  MM --> CO[Colisões]
  LJ --> JG[Jogador]
  JG --> J1[Inventário]
  JG --> J2[Estatísticas]
  JG --> J3[Equipamento]
  LJ --> IN[Inimigos]
  IN --> I1[EstrategiaIA]
  IN --> I2[EstadoIA]
  IN --> I3[Arma e defesa]
  LJ --> IT[Itens loot]
  IT --> T1[Poção]
  IT --> T2[Arma]
  IT --> T3[Ouro]
  LJ --> BE[BarramentoEventos]
  BE --> O1[ObservadorLog]
  BE --> O2[ObservadorUI]
  BE --> O3[ObservadorSom]
  BE --> O4[ObservadorEstatísticas]
  LJ --> GS[GerenciadorSalve]
  GS --> JS[Arquivo JSON]
  LJ --> TA[TelaAscii — View]
  TA --> FB[Frame buffer]
